name: petize_challenge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  http: ^1.2.2
  shared_preferences: ^2.3.5
  webview_flutter: ^4.10.0
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
